module.exports = {
    //font-starts
    fel: { fontFamily: 'PoppinsEL' },
    fl: { fontFamily: 'PoppinsL' },
    fr: { fontFamily: 'PoppinsR' },
    fm: { fontFamily: 'PoppinsM' },
    fsb: { fontFamily: 'PoppinsSB' },
    fbo: { fontFamily: 'PoppinsBO' },
    feb: { fontFamily: 'PoppinsEB' },
    fbl: { fontFamily: 'PoppinsBL' },
    ft: { fontFamily: 'PoppinsT' },
    //font-ends
    //colors-starts
    brandC: { color: '#2eb0e4' },
    liteBlueC: { color: '#eff7fc' },
    yellowC: { color: '#f6b700' },
    liteYellowC: { color: '#fffcf1' },
    blackC: { color: '#525252' },
    liteBlackC: { color: '#7e7e7e' },
    greyC: { color: '#bababa' },
    liteGreyC: { color: '#F4F4F4' },
    lGreyC: { color: '#60604E' },
    whiteC: { color: '#fff' },
    //colors-ends
    //bg-starts
    brandBG: { backgroundColor: '#2eb0e4' },
    liteBlueBG: { backgroundColor: '#eff7fc' },
    yellowBG: { backgroundColor: '#f6b700' },
    liteYellowBG: { cbackgroundColorolor: '#fffcf1' },
    blackBG: { backgroundColor: '#525252' },
    liteBlackBG: { backgroundColor: '#7e7e7e' },
    greyBG: { backgroundColor: '#bababa' },
    liteGreyBG: { backgroundColor: '#F4F4F4' },
    whiteBG: { backgroundColor: '#fff' },
    //bg-ends
    section: {
        flex: 1,
        fontFamily: 'PoppinsR',
        fontSize: 14,
    },
    container: {
        padding: 20,
    },
    flexDR: {
        flexDirection: "row",
        flex: 1,
    },
    flexDC: {
        flexDirection: "column",
    },
    flexDRR: {
        flexDirection: "row-reverse",
    },
    flexDCR: {
        flexDirection: "column-reverse",
    },
    directionLTR: { direction: 'ltr' },
    directionRTL: { direction: 'rtl' },
    justifyContentFS: { justifyContent: 'flex-start' },
    justifyContentFE: { justifyContent: 'flex-end' },
    justifyContentC: { justifyContent: 'center' },
    justifyContentSB: { justifyContent: 'space-between' },
    justifyContentSA: { justifyContent: 'space-around' },
    justifyContentSE: { justifyContent: 'space-evenly' },
    alignItemsS: { alignItems: 'stretch' },
    alignItemsFS: { alignItems: 'flex-start' },
    alignItemsFE: { alignItems: 'flex-end' },
    alignItemsC: { alignItems: 'center' },
    alignItemsB: { alignItems: 'baseline' },
    alignSelfS: { alignSelf: 'stretch' },
    alignSelfFS: { alignSelf: 'flex-start' },
    alignSelfFE: { alignSelf: 'flex-end' },
    alignSelfC: { alignSelf: 'center' },
    alignSelfB: { alignSelf: 'baseline' },
    alignContentS: { alignContent: 'stretch' },
    alignContentFS: { alignContent: 'flex-start' },
    alignContentFE: { alignContent: 'flex-end' },
    alignContentC: { alignContent: 'center' },
    alignContentSB: { alignContent: 'space-between' },
    alignContentSA: { alignContent: 'space-around' },
    flexWrapW: { flexWrap: 'wrap' },
    flexWrapN: { flexWrap: 'no-wrap' },
    flexDRSB: { flexDirection: "row", justifyContent: "space-between" },
    flexDRSA: { flexDirection: "row", justifyContent: 'space-around' },
    flexDRSE: { flexDirection: "row", justifyContent: 'space-evenly' },
    flexDCSB: { flexDirection: "column", justifyContent: "space-between" },
    flexDCSA: { flexDirection: "column", justifyContent: 'space-around' },
    flexDCSE: { flexDirection: "column", justifyContent: 'space-evenly' },
    flexDR_ALC: { flexDirection: "row", alignItems: 'center' },
    flexDR_JCC: { flexDirection: "row", justifyContent: 'center' },
    alignCenter: { alignItems: 'center', justifyContent: 'center' },
    textCenter: {
        textAlign: "center",
    },
    textLeft: {
        textAlign: "left",
    },
    textRight: {
        textAlign: "right",
    },
    borderRadius10: {
        borderRadius: 10,
    },
    borderRadius20: {
        borderRadius: 20,
    },
    borderRadius30: {
        borderRadius: 30,
    },
    //borderR100: { borderRadius: '100%' },
    imgFull: {
        width: "100%",
    },
    img50: { width: 50, height: 50 },
    img100: { width: 100, height: 100 },
    img150: { width: 150, height: 150 },
    imgBR50: { width: 50, height: 50, borderRadius: 50 / 2 },
    imgBR100: { width: 100, height: 100, borderRadius: 100 / 2 },
    imgBR150: { width: 150, height: 150, borderRadius: 150 / 2 },
    spaceB5: { marginBottom: 5 },
    spaceB10: { marginBottom: 10 },
    spaceB20: { marginBottom: 20 },
    spaceB30: { marginBottom: 30 },
    spaceT5: { marginTop: 5 },
    spaceT10: { marginTop: 10 },
    spaceT20: { marginTop: 20 },
    spaceT30: { marginTop: 30 },
    line10: { borderBottomColor: '#ccc', borderBottomWidth: 1, paddingBottom: 10, marginBottom: 10 },
    line20: { borderBottomColor: '#ccc', borderBottomWidth: 1, paddingBottom: 20, marginBottom: 20 },
    padding10: { padding: 10 },
    padding20: { padding: 20 },
    padding30: { padding: 30 },
    paddingL10: { padddingLeft: 10 },
    paddingL20: { padddingLeft: 20 },
    paddingL30: { padddingLeft: 30 },
    paddingR10: { padddingRight: 10 },
    paddingR20: { padddingRight: 20 },
    paddingR30: { padddingRight: 30 },
    marginL10: { marginLeft: 10 },
    marginL20: { marginLeft: 20 },
    marginL30: { marginLeft: 30 },
    marginR10: { marginRight: 10 },
    marginR20: { marginRight: 20 },
    marginR30: { marginRight: 30 },
    //font-size
    f10: { fontSize: 10 },
    f11: { fontSize: 11 },
    f12: { fontSize: 12 },
    f14: { fontSize: 14 },
    f16: { fontSize: 16 },
    f18: { fontSize: 18 },
    f24: { fontSize: 24 },
    //extra-css
    headerTitle: {
        fontSize: 18,
        fontFamily: 'PoppinsSB',
        color: '#fff',
        textTransform: "uppercase",
    },
    backButton: {
        marginRight: 10,
        justifyContent: "center",
    },
    yellowBtn: {
        backgroundColor: '#f6b700',
        width: '70%',
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10
    },
    blueBtn: {
        backgroundColor: '#2eb0e4',
        width: 100,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10
    },
    //modal-css
    centeredView: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    modalView: {
        backgroundColor: "white",
        borderRadius: 10,
        padding: 10,
        height: 150,
        alignItems: "center",
        justifyContent: 'center',
        shadowColor: "#000",
        shadowOffset: {
            width: 2,
            height: 4
        },
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 10,
        width: '90%'
    },
    modalText: {
        marginBottom: 15,
        textAlign: "center",
        color: '#60604E',
        fontSize: 18
    }
}